// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	storm "github.com/asdine/storm/v3"
	mock "github.com/stretchr/testify/mock"
)

// Reader is an autogenerated mock type for the Reader type
type Reader struct {
	mock.Mock
}

// Data provides a mock function with given fields:
func (_m *Reader) Data() *storm.DB {
	ret := _m.Called()

	var r0 *storm.DB
	if rf, ok := ret.Get(0).(func() *storm.DB); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*storm.DB)
		}
	}

	return r0
}
