codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: up
  range: "70...100"
  status:
    project:
      default:
        target: auto
        threshold: 10%
    patch:
      default:
        informational: yes


parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no