name: ogma
base: core20 # the base snap is the execution environment for this snap
version: git # just for humans, typically '1.2+git' or '1.3.2'
summary: Ogma is a pen-pal tracking application # 79 char long summary
description: Ogma is a tracking application for penpals using LEX magazine. It stores a digital record of LEX magazine ads and allows the user to track letters sent and received. Correspondence may also be linked to previous letters or LEX ads.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  ogma:
    command: bin/ogma
    plugs:
      - home

parts:
  ogma:
    plugin: go
    source-type: git
    source: https://github.com/asphaltbuffet/ogma